name: cortisol-aptamer-code
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy
      - pandas
      - scipy
      - scikit-learn
      - joblib
      - torch
      - tqdm
      - httpx
      - fastapi
      - openpyxl
      - matplotlib
